{% set flavor_name = flavor_name or "m1.tiny" %}
---
  CinderVolumes.create_snapshot_and_attach_volume:
    -
      args:
          volume_type: "lvmdriver-1"
          size:
              min: 1
              max: 5
      runner:
        type: "constant"
        times: 4
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 1
        servers:
          image:
            name: "^cirros.*-disk$"
          flavor:
            name: "{{flavor_name}}"
          servers_per_tenant: 2
      sla:
        failure_rate:
          max: 0
    -
      args:
          volume_type: "test"
          size:
              min: 1
              max: 5
      runner:
        type: "constant"
        times: 4
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 1
        servers:
          image:
            name: "^cirros.*-disk$"
          flavor:
            name: "{{flavor_name}}"
          servers_per_tenant: 2
        volume_types:
          - "test"
      sla:
        failure_rate:
          max: 0
