{% set api_version = api_version or "2" %}
{% set service_type = service_type or "volumev2" %}
---
  CinderVolumes.create_and_list_volume:
    -
      args:
        size: 1
        detailed: True
      runner:
        type: "constant"
        times: 3
        concurrency: 1
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        api_versions:
          cinder:
            version: {{api_version}}
            service_type: "{{service_type}}"
      sla:
        failure_rate:
          max: 0
    -
      args:
        size:
          min: 1
          max: 5
        detailed: True
      runner:
        type: "constant"
        times: 3
        concurrency: 1
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        api_versions:
          cinder:
            version: {{api_version}}
            service_type: "{{service_type}}"
      sla:
        failure_rate:
          max: 0
