---
  KeystoneBasic.create_delete_user:
    -
      args:
        name_length: 10
      runner:
        type: "constant"
        times: 100
        concurrency: 10
      sla:
        max_seconds_per_iteration: 4.0
        failure_rate:
          max: 1
        max_avg_duration: 3.0
        outliers:
          max: 1
          min_iterations: 10
          sigmas: 10
