---
  NovaServers.boot_and_associate_floating_ip:
    -
      args:
        flavor:
            name: "m1.tiny"
        image:
            name: "cirros-0.3.2-x86_64-uec"
      runner:
        type: "constant"
        times: 1
        concurrency: 1
      context:
        users:
          tenants: 1
          users_per_tenant: 1
        network: {}
