---
  HttpRequests.check_random_request:
    -
      args:
        requests:
          -
            url: "http://www.example.com"
            method: "GET"
            status_code: 200
          -
            url: "http://www.openstack.org"
            method: "GET"
        status_code: 200
      runner:
        type: "constant"
        times: 20
        concurrency: 5
